### ISSUE TITLE
The Menu drop-down list doesn’t show up in /font-family

### ISSUE THREAD

**Issue by krkk** [Xexxa/fonts.serenityos.net#3]
i.e. clicking this item does nothing
url: https://fonts.serenityos.net/font-family

Expected result:
Menu does show up, like on other pages.
![example screenshot showing the menu](https://user-images.githubusercontent.com/16520278/171059734-0ddc36cd-8d06-48c5-b8aa-fdcccd626d55.png)

**Comment by Xexxa** [comment]
Thank you @krkk for posting this issue. Issue resolved, I accidentally included the bootstrap javascript two times on that page in it broke things...
